server:
  port: 8080
  contextPath: /

spring:
  datasource:
    tomcat:
      max-wait: 5000
      max-active: 20
      test-on-borrow: true
    username: postgres
    password: 1182vekz73
    url: jdbc:postgresql://localhost:5432/server
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  http:
    multipart:
      max-request-size: 5MB
      max-file-size: 12MB

JavaWebIntro:
  timezone: Europe/Moscow
